# Generated by Django 5.2.4 on 2025-09-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('cooking', 'Готовится'), ('delivery', 'Доставка'), ('done', 'Доставлен'), ('cancel', 'Отменён')], default='new', max_length=20),
        ),
    ]
