# Generated by Django 5.2.18 on 2026-10-08 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_orders(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Line = apps.get_model('orders', 'OrderItem')
    Event = apps.get_model('orders', 'OrderEvent')
    for order in Order.objects.select_related('user').all().iterator():
        order.checkout_token = uuid.uuid4()
        order.customer_name = order.user.first_name or order.user.username
        order.phone = order.user.phone or ''
        # Historical 'paid' describes payment, not delivery. Preserve courier assignment.
        if order.status in ('pending', 'paid'):
            order.status = 'delivery' if order.courier_id else 'new'
        order.save(update_fields=['checkout_token', 'customer_name', 'phone', 'status'])
        Event.objects.create(order=order, status=order.status, note='Заказ перенесён из предыдущей версии сервиса.')
    for line in Line.objects.select_related('menu_item').all().iterator():
        line.name = line.menu_item.name
        line.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0005_courier_is_approved_alter_courier_shift_status_and_more'),
        ('menu', '0004_alter_category_options_alter_menuitem_options_and_more'),
        ('orders', '0006_order_latitude_order_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Принят'), ('cooking', 'Готовится'), ('ready', 'Готов к выдаче'), ('delivery', 'Курьер в пути'), ('done', 'Доставлен'), ('cancel', 'Отменён')], max_length=20)),
                ('note', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=500)),
                ('resolution', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_token',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Принят'), ('cooking', 'Готовится'), ('ready', 'Готов к выдаче'), ('delivery', 'Курьер в пути'), ('done', 'Доставлен'), ('cancel', 'Отменён')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menuitem'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['courier', 'status'], name='orders_orde_courier_968f4e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='orders_orde_user_id_0ae59f_idx'),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderissue',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderissue',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='orders.order'),
        ),
        migrations.AddConstraint(
            model_name='orderissue',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('order',), name='one_open_issue_per_order'),
        ),
        migrations.RunPython(backfill_orders, migrations.RunPython.noop),
        migrations.AlterField(model_name='order', name='checkout_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
    ]
