# Generated by Django 5.2.18 on 2026-10-09 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0006_courier_last_delivery_at_courier_latitude_and_more'),
        ('orders', '0007_orderevent_orderissue_alter_order_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тёпло', max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('preparation_minutes', models.PositiveSmallIntegerField(default=15)),
                ('accepting_orders', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'кухня и доставка',
                'verbose_name_plural': 'Кухня и доставка',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('work_kitchen', 'Работать с очередью кухни')], 'verbose_name': 'заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dispatch_alert',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DeliveryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Предложен'), ('accepted', 'Зарезервирован'), ('declined', 'Отказ'), ('expired', 'Нет ответа'), ('cancelled', 'Снят'), ('picked_up', 'Забран')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_minutes', models.PositiveSmallIntegerField(default=0)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='courier.courier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'expires_at'], name='orders_deli_state_a25ca7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state__in', ['pending', 'accepted'])), fields=('order',), name='one_live_offer_per_order'), models.UniqueConstraint(condition=models.Q(('state__in', ['pending', 'accepted'])), fields=('courier',), name='one_next_offer_per_courier')],
            },
        ),
    ]
