# Generated by Django 5.2.18 on 2026-10-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_restaurant_alter_order_options_order_delivery_eta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='last_dispatch_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
