# Generated by Django 5.2.18 on 2026-10-08 19:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def clean_prices(apps, schema_editor):
    # Existing non-positive prices must be reviewed before the item is sold again.
    apps.get_model('menu', 'MenuItem').objects.filter(price__lte=0).update(price=1, is_available=False)


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['id'], 'verbose_name': 'блюдо', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='badge',
            field=models.CharField(blank=True, max_length=30, verbose_name='Метка'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_vegetarian',
            field=models.BooleanField(default=False, verbose_name='Без мяса'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='seed_image',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='weight',
            field=models.CharField(blank=True, max_length=30, verbose_name='Вес / объём'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='menu.category'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.RunPython(clean_prices, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='menu_price_positive'),
        ),
    ]
