# Generated by Django 5.2.18 on 2026-10-08 19:44

from django.db import migrations, models


def clean_cart(apps, schema_editor):
    Line = apps.get_model('cart', 'CartItem')
    seen = {}
    for line in Line.objects.order_by('pk').iterator():
        key = (line.cart_id, line.menu_item_id)
        if key in seen:
            original = seen[key]
            original.quantity = min(30, original.quantity + line.quantity)
            original.save(update_fields=['quantity'])
            line.delete()
        else:
            line.quantity = max(1, min(30, line.quantity))
            line.save(update_fields=['quantity'])
            seen[key] = line

    # Flush deferred FK checks before the following schema operations on PostgreSQL.
    # Keep data cleanup and schema changes in the same atomic migration.
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('SET CONSTRAINTS ALL IMMEDIATE')


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_created_at_and_more'),
        ('menu', '0004_alter_category_options_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.RunPython(clean_cart, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'menu_item'), name='one_item_per_cart'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 30)), name='cart_quantity_range'),
        ),
    ]
