# Generated by Django 5.2.6 on 2025-10-06 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_address_order_courier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта')], max_length=10)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('confirmed', 'Оплачено'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
