# Generated by Django 5.2.4 on 2025-09-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Клиент'), ('courier', 'Курьер'), ('admin', 'Админ')], default='customer', max_length=20),
        ),
    ]
