# Generated by Django 5.2.18 on 2026-10-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Покупатель'), ('courier', 'Курьер'), ('admin', 'Администратор')], default='customer', max_length=20),
        ),
    ]
