# Generated by Django 5.2.6 on 2025-10-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='courier',
            name='shift_status',
            field=models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен'), ('busy', 'Занят')], default='active', max_length=20, verbose_name='Статус смены'),
        ),
        migrations.AddField(
            model_name='courier',
            name='vehicle_type',
            field=models.CharField(choices=[('foot', 'Пеший'), ('bike', 'Велосипед'), ('car', 'Машина'), ('scooter', 'Скутер')], default='foot', max_length=20, verbose_name='Транспорт'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
    ]
