# Generated by Django 5.2.6 on 2025-10-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_remove_courier_vehicle_courier_shift_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='vehicle_type',
            new_name='vehicle',
        ),
    ]
