# Generated by Django 5.2.18 on 2026-10-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0004_courier_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрен администратором'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='shift_status',
            field=models.CharField(choices=[('active', 'На смене'), ('inactive', 'Не на смене'), ('busy', 'На доставке')], default='inactive', max_length=20, verbose_name='Смена'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='vehicle',
            field=models.CharField(choices=[('foot', 'Пешком'), ('bike', 'Велосипед'), ('car', 'Автомобиль'), ('scooter', 'Скутер')], default='foot', max_length=20, verbose_name='Транспорт'),
        ),
    ]
